version: "3"

services:
  web:
    build: web
    ports:
      - "3000:3000"
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=12345678"
    links:
      - db
    volumes:
      - "./app:/app"
    tty: true
    stdin_open: true

  db:
    image: postgres:11.1
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=12345678"
    volumes:
      - datavol:/var/lib/postgresql/data

volumes:
  datavol:
